apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daedalus
rules:
  -
    apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
      - networking.istio.io
      - authentication.istio.io
      - cert-manager.io
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - statefulsets
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - virtualservices
      - policies
      - certificates
      - gateways
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daedalus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: daedalus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: daedalus
subjects:
- kind: ServiceAccount
  name: daedalus
  namespace: default
